live_config_reload = true

[window]
decorations = "Buttonless"
padding = { x = 12, y = 12 }

[font]
normal = { family = "Iosevka", style = "Regular" }
size = 16

[colors]
[colors.primary]
background = "#24273a"
